name: seekerpay_qr
description: QR code generation and scanning for SeekerPay.
version: 1.2.0
topics:
  - solana
  - payments
  - qr-code
  - blockchain
  - web3
homepage: https://github.com/vasuthammaiah/spay-sdk
repository: https://github.com/vasuthammaiah/spay-sdk
issue_tracker: https://github.com/vasuthammaiah/spay-sdk/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  seekerpay_core: ^1.2.0
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
