name: seekerpay_ui_example
description: Example app for seekerpay_ui.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  seekerpay_core: ^1.0.0
  seekerpay_ui: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
