name: seekerpay_split
description: Social payments and group splits for SeekerPay.
version: 1.1.1
topics:
  - solana
  - payments
  - blockchain
  - wallet
  - web3
homepage: https://github.com/vasuthammaiah/spay-sdk
repository: https://github.com/vasuthammaiah/spay-sdk
issue_tracker: https://github.com/vasuthammaiah/spay-sdk/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  seekerpay_core: ^1.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
