name: seekerpay_bluetooth
description: Bluetooth and Nearby Connections for SeekerPay.
version: 1.0.5
topics:
  - solana
  - payments
  - bluetooth
  - networking
  - web3
homepage: https://github.com/vasuthammaiah/spay-sdk
repository: https://github.com/vasuthammaiah/spay-sdk
issue_tracker: https://github.com/vasuthammaiah/spay-sdk/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  nearby_connections: ^4.3.0
  permission_handler: ^11.3.1
  seekerpay_core: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
