name: seekerpay_ui
description: Reusable UI components for SeekerPay payments.
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  seekerpay_core:
    path: ../seekerpay_core
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
